### PR TITLE
add PARTITION BY option for CopyInto

### LINKED ISSUE #430: SNOW-878116: `CopyInto` does not support the `PARTITION BY` clause
## What is the current behavior?

`CopyInto` does not support the `PARTITION BY` clause

## What is the desired behavior?

`CopyInto` supports the `PARTITION BY` clause

## How would this improve `snowflake-connector-python`?
 
This would allow users to use the `PARTITION BY` clause which is a documented feature of the `COPY INTO` statement

## References, Other Background

https://docs.snowflake.com/en/sql-reference/sql/copy-into-location

### PR DESCRIPTION
**Pull request by azban**
Please answer these questions before submitting your pull requests. Thanks!

1. What GitHub issue is this PR addressing? Make sure that there is an accompanying issue to your PR.

   Fixes #430 

2. Fill out the following pre-review checklist:

   - [x] I am adding a new automated test(s) to verify correctness of my new code
   - [ ] I am adding new logging messages
   - [ ] I am adding new credentials
   - [ ] I am adding a new dependency

3. Please describe how your code solves the related issue.

This adds an argument to `CopyInto` which can be used to specify a string value for `PARTITION BY`. I have a few questions about implementation:

1. Would it be better to adhere to the convention of having functions that do some validation similar to those used for `CopyInto.copy_options`? If so, is there any particular validation to make sense?
2. Is there a preference towards implementing this as a clause rather than allowing for a string? I'm not very familiar with custom clauses, and I don't know of a similar implementation that would be useful to base this on.
3. Unrelated to implementation, but is there a straightforward way to run tests locally? i.e. is there an example parameters file that can be used?

### CODE REVIEW

**Comment by azban** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by azban** [comment]
recheck

**Comment by azban** [comment]
can anyone take a look at this?

**Comment by azban** [comment]
what's the process for this repo considering and accepting PR's? should we assume we should maintain our own forks long-term?

**Comment by azban** [comment]
bump

**Comment by afavaro** [comment]
@sfc-gh-dszmolka @sfc-gh-astus @sfc-gh-mraba 

Any chance we could get a review on this? We're still maintaining our own fork of this library so that we can use this feature.

**Comment by sfc-gh-lcalderonachio** [comment]
Hi @azban 
Thanks for your contribution, these changes have been merged in https://github.com/snowflakedb/snowflake-sqlalchemy/pull/542 with some additional changes. I'll be closing this PR now

**Pull request closed without merging**
