### PR TITLE
fix orm schema translate map double quoting issue

### PR DESCRIPTION
**Pull request by meoril**
Fix issue #247 
This fixes the way _split_schema_by_dot changes the return value of the schema parameter from quoted_name to str.

### CODE REVIEW

**Comment by sfc-gh-sbommakanty** [comment]
Hi @meoril - before we can proceed with the PR, wanted to check if you've signed a CLA?  Please provide your name so we can confirm. Thank you!

**Comment by meoril** [comment]
Hi @sfc-gh-sbommakanty thanks for the response! We're reviewing the CLA terms (just some internal bureaucracy stuff :/) and we'll update immediately once it's signed :)

**Review by sfc-gh-mkeller — APPROVED** [review]
I see, so by returning `str`s we strip away the possible `quote` arguments from them.

Please, don't be alarmed I modified your test a little bit. Thank you so much for your contribution.

Please do sign our CLA!

**Comment by meoril** [comment]
@sfc-gh-mkeller thanks! and yes exactly :) I've just converted the strings list to `quoted_name`s list and copied the main original attributes to it.
Regarding the CLA signing, this will be done hopefully during the next couple of days.

**Comment by meoril** [comment]
Hi @sfc-gh-mkeller, I just wanted to updated that I've signed the CLA.

image

**Pull request merged**
