### PR TITLE
Add TIMESTAMP_LTZ type; make type compiler emit TIME ZONE

### LINKED ISSUE #59: Table objects with TIMESTAMP(timezone=True) columns don't produce TIMESTAMP_TZ columns in Snowflake
Python: 2.7.10
Platform: Darwin-16.7.0-x86_64-i386-64bit

pip:

snowflake-sqlalchemy==1.1.2
# snowflake-connector-python==1.6.8 # Installed as dependency for snowflake-sqlalchemy
# sqlalchemy==1.2.11 # Installed as dependency for snowflake-sqlalchemy, alembic

I attempted to take a logical Table object in SQLA and invoke `create(bind=my_snowflake_engine)`. The table was created, but the columns whose type was `TIMESTAMP(timezone=True)` became `TIMESTAMP_NTZ` columns in the Snowflake table instead of `TIMESTAMP_TZ`.

Also, I see no way to specify TIMESTAMP_LTZ as a data type for any column.

### PR DESCRIPTION
**Pull request by robin900**
Fixes #59 .

### CODE REVIEW

**Comment by smtakeda** [comment]
thanks for PR. will take a look.

**Comment by robin900** [comment]
@smtakeda I am currently having to use a custom-built wheel for `snowflake-sqlalchemy` to gain the TIMESTAMP_*Z proper type support. I'd like to have my team use the PyPI version to simplify our deployment challenges. Any chance we could review the PR soon?

**Comment by smtakeda** [comment]
I'm stuck with other tasks in ODBC and JDBC currently, so it would be helpful if you provide a test case part of test_core.py :)

**Comment by smtakeda** [comment]
@robin900 any small test case would be helpful. Thanks.

**Comment by robin900** [comment]
@smtakeda i've added the draft of a test case to the PR. I cannot get any tests to execute; I'm stuck at a failure in conftest.py: 
```
ImportError while loading conftest '/Users/rthomas/git/snowflake-sqlalchemy/test/conftest.py'.
../../.virtualenvs/snowflake-sqlalchemy/lib/python2.7/site-packages/six.py:709: in exec_
    exec("""exec _code_ in _globs_, _locs_""")
test/conftest.py:19: in <module>
    from snowflake.sqlalchemy import URL
E   ImportError: No module named sqlalchemy
```

**Comment by smtakeda** [comment]
no worry, @robin900 . I've already added a test case and merged to master.
We'll release v1.1.3 next week.

**Pull request closed without merging**
